version: "3.9"

services:
  stopmotion-backend:
    image: ghcr.io/malin-radek/malin-stopmotion:latest
    ports:
      - "8000:8000"
    environment:
      - PHONE_IP=${PHONE_IP:-192.168.1.100}
      - PHONE_PORT=${PHONE_PORT:-8081}
    volumes:
      - ./projects:/app/projects
    restart: unless-stopped
    network_mode: host   # host-network żeby dosięgnąć telefonu w tej samej sieci WiFi
