version: "3.9"

services:
  stopmotion-backend:
    build: .
    image: ghcr.io/malin-radek/malin-stopmotion:latest
    environment:
      - PHONE_IP=${PHONE_IP:-192.168.10.12}
      - PHONE_PORT=${PHONE_PORT:-8081}
      - PROJECTS_DIR=/app/projects
    volumes:
      - ./projects:/app/projects
    restart: unless-stopped
    network_mode: host   # host-network: backend/GUI pod :8000 i dostep do telefonu w tej samej sieci WiFi
